# Generated by Django 3.2 on 2021-05-14 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solar_lookup', '0004_alter_satelliteimagery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteimagery',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='satelliteimagery',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='satelliteimagery',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
