# Generated by Django 3.2 on 2021-05-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_lookup', '0006_satelliteimagery_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteimagery',
            name='address',
        ),
        migrations.AddField(
            model_name='satelliteimagery',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='satelliteimagery',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
