# Generated by Django 3.2.3 on 2021-05-17 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arraymodel',
            name='id',
        ),
        migrations.AddField(
            model_name='arraymodel',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='arraymodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='arraymodel',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
