# Generated by Django 3.2.3 on 2021-05-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_builder', '0004_auto_20210517_0250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArrayModel',
        ),
    ]
