# Generated by Django 3.2.3 on 2021-05-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_builder', '0005_delete_arraymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarArraySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelsInfo', models.JSONField()),
            ],
        ),
    ]
